version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: akshaysdev/library-v1.0:latest
    networks:
      - library-net
    ports:
      - 8000:8000
    environment:
      - TZ=Asia/Kolkata
    container_name: server
    working_dir: /home/apps/library/
    volumes:
      - ~/personal/assignments/Library:/home/apps/library
      - node_modules:/home/apps/library/node_modules
    depends_on:
      mongo_db:
        condition: service_healthy
    command: npm start

  mongo_db:
    image: mongo:5.0.8
    networks:
      - library-net
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - ~/personal/dbs/mongo:/data/db
    command: --quiet --logpath /dev/null
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/healthcheck-database --quiet

networks:
  library-net:

volumes:
  node_modules: